=== giellalt/dict-sjd-mul/scripts/dictionary.dtd
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"      
	  xml:lang ( sjd ) #IMPLIED
>
<!ATTLIST r 
      id ( sjd2x ) #IMPLIED >

      
<!-- the header and licence notes -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!-- the entry; "e+" = means ≥1 entries in the dictionary -->
<!-- source attributues are copied from another project and are perhaps not needed here [src ( nj | sk | SvSt | gt_fad | gt | fad | other ) #IMPLIED] -->
<!-- "CDATA" in kur_ID need to be checked, the relevant values are all numerals; but is ku_ID really needed? -->
<!-- do we need usuage attributes? [usage ( FST | NDS | OAH ) #IMPLIED] -->
<!ELEMENT e (note?, lg, mg+) >
<!ATTLIST e
      kur_ID CDATA #IMPLIED
>

<!ELEMENT note (#PCDATA) >

<!--  the lemma group; "mg+" = means ≥1 meanings in the entry -->
<!-- for more potential types, see the GT dtd  -->
<!ELEMENT lg (l, orth*, stem*, compare*, der*) >
<!ELEMENT l (#PCDATA) >
<!ATTLIST l 
      pos       (   A | Adp | Adv | CC | CS | Det | Interj | N | Num | Pcle | Pron | Prop | V | 
                    Phrase_A | Phrase_Adv | Phrase_N | Phrase_V |
                    S |
                    Der_N |
                    Cmp_N |
                    Mwe |
                    Suf-A | Suf-Adv | Suf-N | Suf-V |
                    xxx
                ) #REQUIRED
      pos_type  (   ad | post | pre | 
                    rel | pers | indef | refl | 
                    ord ) #IMPLIED
      nr        ( Sg | Pl ) #IMPLIED
      person    (3) #IMPLIED
>      
<!-- I need to check what attributes are really useful here
attr ( ok | no ) #IMPLIED
      decl ( 1 | 2 | 3 | 4 | 5 | x | i ) #IMPLIED 
      gen_only CDATA #IMPLIED
      context CDATA #IMPLIED
      pg ( yes | no ) #IMPLIED
      p3p CDATA #IMPLIED
      minip ( notSg1 | onlyPl ) #IMPLIED
      illpl ( ok | no ) #IMPLIED
      status ( sjekk | ok ) #IMPLIED
      grad ( pos | comp | sup ) #IMPLIED
      vmax ( 2 | 3 | 4) #IMPLIED
      base CDATA #IMPLIED
      dialect CDATA #IMPLIED
      soggi CDATA #IMPLIED
      rime CDATA #IMPLIED
      margo CDATA #IMPLIED
      vow CDATA #IMPLIED
      diph ( yes ) #IMPLIED
      umlaut ( full ) #IMPLIED
      num ( pl ) #IMPLIED
      val ( IV | TV ) #IMPLIED
-->

<!ELEMENT orth (lvar+) >
<!ELEMENT lvar (#PCDATA) >
<!ATTLIST lvar
    orth ( 1985kuru | 1986kert | 1986ker1 | 2008sars | 2008sar1 | 2008sar2 ) #IMPLIED       
    >

<!-- the stem group; several values in the fields in this group are inherited from digitalized data -->
<!-- usefull here would perhaps be syll="1|2|3" pala="n|y""
<!ATTLIST stem 
      class ( bisyllabic | trisyllabic | contracted ) #IMPLIED
-->
<!ELEMENT stem (stem_sars*, stem_kert*, stem_kuru*, class_kuru*) >
<!ELEMENT stem_sars (#PCDATA) >
<!ELEMENT stem_kert (#PCDATA) >
<!ATTLIST stem_kert
    nr (Pl) #IMPLIED
    >
<!ELEMENT stem_kuru (#PCDATA) >
<!ATTLIST stem_kuru
    case (Nom) #IMPLIED
    nr (Pl) #IMPLIED
    >
<!ELEMENT class_kuru EMPTY >
<!ATTLIST class_kuru
    class ( I | II | III | IV | V) #IMPLIED
    ablaut (_x_ | 1) #IMPLIED
    special (_x_ | ASTERISK) #IMPLIED
    >
    
<!ELEMENT der (#PCDATA) >
<!ATTLIST der
    type (SM | STRAD_K | PONUD_K) #IMPLIED 
    >

<!ELEMENT compare (#PCDATA) >

<!ELEMENT mg (semantics?, sources?, (lexicon?|tg+)+, xg*) >

<!ELEMENT semantics (sem+, tam*) >
<!ELEMENT sem EMPTY >
<!ATTLIST sem
    class CDATA #IMPLIED
    >      
<!ELEMENT tam (#PCDATA) >

<!ELEMENT sources (book*) >
<!ELEMENT book EMPTY >
<!ATTLIST book 
      name (100 | 200 | 1000 | 2008sars) #IMPLIED
      chap ( 1 ) #IMPLIED
>

<!ELEMENT lexicon (#PCDATA) >
<!ATTLIST lexicon 
      xml:lang ( rus ) #IMPLIED
      >

<!ELEMENT tg (t+, re?, te?, valency?) >
<!ATTLIST tg 
      xml:lang ( rus ) #IMPLIED
      term (medicine) #IMPLIED
>

<!ELEMENT t (#PCDATA) >
<!ATTLIST t
    pos       (   A | Adp | Adv | CC | CS | Det | Interj | N | Num | Pcle | Pron | Prop | V | 
                  Phrase_A | Phrase_Adv | Phrase_N | Phrase_V |
                  S | T |
                  Der_N |
                  Cmp_N |
                  Mwe |
                  Suf-A | Suf-Adv | Suf-N | Suf-V |
                  xxx
                ) #REQUIRED
    pos_type (  ad | post | pre ) #IMPLIED
    nr ( Sg | Pl ) #IMPLIED  
    gen ( m | f | n | xxx ) #IMPLIED
    coda CDATA #IMPLIED
    sem-cl ( figurative | literal-figurative | UNPERS) #IMPLIED
    stat ( pref | notpref | perhaps ) #IMPLIED
    impf CDATA #IMPLIED 
>

<!ELEMENT re (#PCDATA) > <!-- Domain restriction: botanics, physics, ... -->
<!ATTLIST re xml:lang ( rus ) #IMPLIED
>

<!ELEMENT te (#PCDATA) > <!-- Translation explanation -->
<!ATTLIST te xml:lang ( rus ) #IMPLIED >

<!ELEMENT valency EMPTY >
<!ATTLIST valency
    val ( кого | кого-что | ком-чём | кому | над_чем | чего) #IMPLIED
    >

<!ELEMENT xg ((x, xtg+)+) >
<!ATTLIST xg
    source (1985kuru | 1986kert | 2008sarsina1-adposition | 2008sarsina1-tense) #IMPLIED
    lemma  CDATA #IMPLIED
    >
    
<!ELEMENT x (#PCDATA)>
<!ATTLIST x
      pos       (   A | Adp | Adv | CC | CS | Det | Interj | N | Num | Pcle | Pron | Prop | V | 
                    Phrase_A | Phrase_Adv | Phrase_N | Phrase_V |
                    S | T |
                    Der_N |
                    Cmp_N |
                    Mwe |
                    Suf-A | Suf-Adv | Suf-N | Suf-V |
                    xxx
                ) #REQUIRED
    pos_type ( idiom ) #IMPLIED
    orth ( 1985kuru | 1986kert | 1986ker1 | 2008sars) #IMPLIED
>

<!ELEMENT xtg (xt+, xtl?) >
<!ATTLIST xtg
    xml:lang ( rus ) #IMPLIED
 >
 
<!ELEMENT xt (#PCDATA)>
<!ATTLIST xt 
      pos       (   A | Adp | Adv | CC | CS | Det | Interj | N | Num | Pcle | Pron | Prop | V | 
                    Phrase_A | Phrase_Adv | Phrase_N | Phrase_V |
                    S | T |
                    Der_N |
                    Cmp_N |
                    Mwe |
                    Suf-A | Suf-Adv | Suf-N | Suf-V |
                    xxx
                ) #REQUIRED
    pos_type (idiom | proverb) #IMPLIED
    sem-cl ( figurative | literal-figurative) #IMPLIED
 >

<!ELEMENT xtl (#PCDATA)> <!-- literal translation -->
<!ATTLIST xtl 
    pos       (   A | Adp | Adv | CC | CS | Det | Interj | N | Num | Pcle | Pron | Prop | V | 
                    Phrase_A | Phrase_Adv | Phrase_N | Phrase_V |
                    S | T |
                    Der_N |
                    Cmp_N |
                    Mwe |
                    Suf-A | Suf-Adv | Suf-N | Suf-V |
                    xxx
                ) #REQUIRED
    >

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-sjd-mul/src/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet title="Dictionary view" media="screen,tv,projection" href="../../scripts/gt_dictionary.css" type="text/css"?>
<?xml-stylesheet alternate="yes" title="Hierarchical view" media="screen,tv,projection" href="../../scripts/gt_dictionary_alt.css" type="text/css"?>
<!DOCTYPE r
  PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../scripts/dictionary.dtd">
<r id="sjd2x" xml:lang="sjd">
    <lics xml:space="preserve">
 <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
 <ref>Work by Giellatekno at UiT – Norges Arktiske Universitet, University of Freiburg, and members of the Kildin Saami language community. Source code available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
 <sourcenote>
 THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
 published dictionary. As such it can and
 will contain unfinished entries, unpublished entries, entries with
 objectionable translations, etc. If you find any errors or want to add more
 words, download the file, edit it, and send it back to
 <a>mailto:divvun@samediggi.no</a> or <a>mailto:giellatekno@hum.uit.no</a>.
 Please also note that the entries are not necessarily sorted,
 or could be wrongly sorted.
 </sourcenote>
 </lics>

    <e>
        <lg>
            <l pos="N" orth="1985kuru">ба̄йна</l>
            <orthography>
                <lvar orth="1986kert">ба̄йна</lvar>
                <lvar orth="1986ker1">байна</lvar>
            </orthography>
        </lg>
        <mg>
            <semantics>
                <sem class="xxx"/>
            </semantics>
            <tg>
                <t>баня</t>
            </tg>
            <xg>
                <x orth="1985kuru" pos="V">ба̄йнасьт лоавкнэдтэ</x>
                <xt>мыться в бане</xt>
            </xg>
            <xg>
                <x orth="1985kuru" pos="V">ба̄йнасьт поаррдэдтэ</x>
                <xt>париться в бане</xt>
            </xg>
            <xg>
                <x orth="1985kuru" pos="V">вӯллькэ ба̄йная</x>
                <xt>пойти в баню</xt>
            </xg>
            <xg>
                <x orth="1985kuru" pos="xxx" type="idiom">вӯзьхэ ба̄йна ке̄з-не</x>
                <xt>задать баню кому-либо</xt>
            </xg>
        </mg>
    </e>
    <e>
        <lg>
            <l pos="N" orth="1986kert">ба̄јјк</l>
            <orthography>
                <lvar orth="1986kert">ба̄йхьк</lvar>
            </orthography>
            <stem>xxx</stem>
        </lg>
        <mg>
            <tg xml:lang="rus">
                <t pos="N">работа</t>
            </tg>
        </mg>
        <mg>
            <tg xml:lang="rus">
                <t pos="N">сказка</t>
            </tg>
        </mg>
        <mg>
            <tg xml:lang="rus">
                <t pos="N">басня</t>
            </tg>
        </mg>
    </e>
</r>
